values =
[
  "STEM",
  "Scholarships - Apply, apply, apply!",
  "Someone mentions Water Game",
  "Past Game piece in Kickoff stream",
  "Haveabanana Productions",
  "Dean Kamen is wearing denim",
  "Woodie Flowers in a steampunk costume",
  "Gracious Professionalism",
  "Dean's Homework",
  "Encryption Password is 1337",
  "Scripted role-play with steampunk theme",
  "Scramble to download the game manual",
  "Dozer is in the game animation",
  "Someone is sad because Dozer's not in the game animation",
  "One of the animation robots has a plunger",
  "The team eats a meal together",
  "Someone in the room tweets and ends up in the livestream",
  "Someone references previous year's game",
  "Sponsor animation loops more than once",
  "Rule update before the end of the day",
  "Someone's theory about the game is right",
  "Bumpers",
  "Can't download the game manual",
  "The livestream goes down",
  "Coopertition",
  "Mentor Appreciation"
];
