values =
[
  "STEM over STEAM",
  "Scholarships - Apply, apply, apply!",
  "Water Game",
  "Past Game piece in Kickoff stream",
  "Havabanana Productions",
  "Dean Kamen is wearing denim",
  "Woodie Flowers in a steampunk costume",
  "Gracious Professionals",
  "Dean's Homework",
  "Encryption Password is 1337",
  "Scripted role-play with steampunk theme",
  "Scramble to download the game manual",
  "Dozer is in the game animation",
  "Sad because Dozer's not in the game animation",
  "One of the animation robots has a plunger",
  "The team eats a meal together",
  "The team's twitter ends up in the livestream",
  "Someone references last year's game",
  "Sponsor animation loops more than once",
  "Rule update before the end of the day",
  "Someone's theory about the game is right",
  "A theory is completely wrong",
  "Bumpers",
  "Can't download the game manual",
  "The livestream goes down",
  "Someone mentions Coopertition",
  "Mentor Appreciation",
  "Someone asks when food will be ready",
  "FRC related song parody",
  "Last year's design is referenced",
  '"Is this Battle Bots?"',
  "Someone wonders about scouting",
  "Field component plans don't make sense",
  "People argue about a basic rule",
  "Swerve Drive",
  "Game pieces are used incorrectly",
  "Water game is <i>actually</i> confirmed",
  '"Has anyone checked Chief Delphi yet?"',
  "War flashbacks to Recycle Rush",
  "Dean Kamen is riding a segway",
  "Alumni come to Kickoff",
  "Winning chairmans' video",
  "Safety animation winner",
  "Frank Merrick, Director of FRC",
  "Humans pretending to be robots",
  "Blobby humans in animation",
  "Animation robots are impossible",
  "New FIRST sponsor",
  "Surprise items in KOP",
  "Help for rookie teams",
  "Update on FIRST growth",
  "Technical Difficulties",
  "Robot does everything suggestion",
  "A game hint is taken seriously",
  '"Good luck, and see you at the competition"',
  "Something falls on Dozer"
];
